# Generated by Django 4.0.4 on 2022-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cmail',
            field=models.EmailField(default='umesh@gmail.com', max_length=254),
        ),
    ]
