# Generated by Django 4.0.4 on 2022-04-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('eadd', models.CharField(max_length=500)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
